server:
  port: 22100
spring:
  application:
    name: xc-service-base-filesystem
#mongo配置
  data:
    mongodb:
      database: xc_fs
      uri: mongodb://root:123@127.0.0.1:27017
#SpringMVC上传文件配置
  servlet:
    multipart:
      #默认支持文件上传.
      enabled: true
      #支持文件写入磁盘.
      file-size-threshold: 0
      # 上传文件的临时目录
      location:
      # 最大支持文件大小
      max-file-size: 1MB
      # 最大支持请求大小
      max-request-size: 30MB
xuecheng:
  fastdfs: #配置fast-DFS图片文件服务器
    connect_timeout_in_seconds: 30000
    network_timeout_in_seconds: 30000
    charset: UTF-8
    #虚拟机中的tracker server地址以及端口号
    tracker_servers: 192.168.211.143:22122 #多个 trackerServer中间以逗号分隔