server:
  port: 31002

spring:
  application:
    name: xc-service-manage-cms-client
  data:
    mongodb:
      uri: mongodb://root:123@localhost:27017
      database: xc_cms
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtualHost: /

xuecheng:
  mq:
  #cms客户端监控的队列名称（不同的客户端监控的队列不能重复）
    queue: queue_cms_postpage_03 #在配置文件中配置队列的名称，每个 cms client在部署时注意队列名称不要重复
    routingKey: 5e885693083c8940382e70c5  #此routingKey为门户站点ID
